📝 Update data log
The-Strategy-Unit/nhp_project_information pull request #136
Opened 2024-11-12 14:43 UTC by StatsRhian

I've made a start on the data log

2024-11-12 23:22 UTC, StatsRhian commented on data_extraction/data_log.qmd
> +As part of migrating our data processing from SQL to databricks, we have a made a number of changes to the data.
Great shout. Added. 🙏🏻

2024-11-12 23:23 UTC, StatsRhian commented on data_extraction/data_log.qmd
> + - evidence based interventions: update code lists
@tomjemmett any specific bits you want to highlight here? Could be lines of code, or commits.

2024-11-13 12:28 UTC, yiwen-h approved these changes
Happy to approve but just want final final confirmation from @tomjemmett before merge!

2024-11-13 22:04 UTC, tomjemmett requested changes
mostly looks fine, we are missing:

Inpatients
- alcohol_partially_attributable: errors in the old code list meant some codes were missed, and some codes were not properly distinguishing between the mortality/morbidity cases
- excess_beddays: an error in the way we handled the old csv meant some NA values were treated as 0, flagging most activity as being an excess bedday

2024-11-13 22:39 UTC, tomjemmett requested changes

2024-11-13 22:39 UTC, tomjemmett commented on data_extraction/data_log.qmd
> +Inpatient mitigators:
```suggestion
  - Added a new flag `maternity_delivery_in_spell`, which looks to see if any episode in the spell had `maternity_episode_type=1`, the same [logic used to create the official published statistics on delivery episodes](https://digital.nhs.uk/data-and-information/publications/statistical/nhs-maternity-statistics) (applied at spell end level)
Inpatient mitigators:
```

2024-11-14 09:06 UTC, yiwen-h commented on data_extraction/data_log.qmd
> +We have migrated our data pre-processing pipeline from SQL to Databricks. The new data pre-processing scripts are available in the public repository [nhp_data](https://github.com/The-Strategy-Unit/nh
Nah I think don't bother

2024-11-14 09:06 UTC, yiwen-h commented on data_extraction/data_log.qmd
> +We have migrated our data pre-processing pipeline from SQL to Databricks. The new data pre-processing scripts are available in the public repository [nhp_data](https://github.com/The-Strategy-Unit/nh
Plan is just to archive and state there are known bugs I think

2024-11-14 10:49 UTC, tomjemmett approved these changes
lgtm

2024-11-14 10:53 UTC, merged