🔊 Add model updates v3.0
The-Strategy-Unit/nhp_project_information pull request #138
Opened 2024-11-13 15:07 UTC by StatsRhian

Initial model update

2024-11-13 15:07 UTC, StatsRhian commented on project_plan_and_summary/model_updates.qmd
> +A&E data now includes A&E follow-up activity. This may mean that you seen larger numbers in A&E data in v3.0 onwards. The outputs app currently does not seperate out this activity, but it is availabl
```suggestion
A&E data now includes A&E follow-up activity. This may mean that you see larger numbers in A&E data in v3.0 onwards. The outputs app currently does not seperate out this activity, but it is available in the data downloads.
```

2024-11-13 17:29 UTC, yiwen-h requested changes
I think we need to elaborate on all the [changes that have happened to support conversion to capacity](https://github.com/The-Strategy-Unit/nhp_planning/issues/17), including:
- additional LOS categories
- acuity and followups in A&E data (you've already mentioned the followups)

2024-11-13 17:29 UTC, yiwen-h commented on project_plan_and_summary/model_updates.qmd
> +The reason that it is a major release is that the pipeline for data pre-processing has been migrated from SQL to Databricks.The new data pre-processing scripts are available in the public repository
```suggestion
The reason that it is a major release is that the pipeline for data pre-processing has been migrated from SQL to Databricks. The new data pre-processing scripts are available in the public repository [nhp_data](https://github.com/The-Strategy-Unit/nhp_data). This repository supersedes the [nhp_sql](https://github.com/The-Strategy-Unit/nhp_sql) repository which will be publicly archived and no longer maintained.
```

2024-11-13 17:30 UTC, yiwen-h commented
I can work on adding the extra stuff tomorrow AM :)

2024-11-14 10:11 UTC, yiwen-h approved these changes

2024-11-14 10:24 UTC, merged